import streamlit as st
import pandas as pd

# --- PAGE CONFIG ---
st.set_page_config(page_title="Retainlytics Command Center", page_icon="📊", layout="wide")

# --- HEADER ---
st.title(" Retainlytics Command Center")
st.markdown("### Engineering Leadership in Customer Retention")
st.markdown("This dashboard operationalizes the **70/50 Rule**: Intervene only when **Churn Probability ≥ 70%** AND **Monthly Revenue ≥ $50**.")

# --- LOAD DATA ---
@st.cache_data
def load_data():
    try:
        # Reads the leakage-free holdout data generated by Phase 6 in Colab
        df = pd.read_csv('dashboard_scoring_data.csv')
        return df
    except FileNotFoundError:
        st.error("⚠️ Data file not found. Ensure 'dashboard_scoring_data.csv' is inside the 'outputs/data/' folder.")
        return pd.DataFrame()

df = load_data()

if not df.empty:
    # --- STRATEGY LOGIC (The 70/50 Gate) ---
    prob_threshold = 0.70
    rev_threshold = 50.0
    
    high_risk = df[df['Churn_Probability'] >= prob_threshold]
    whales_at_risk = high_risk[high_risk['MonthlyRevenue'] >= rev_threshold]
    
    # --- EXECUTIVE METRICS ---
    col1, col2, col3 = st.columns(3)
    
    with col1:
        st.metric(label="Total Test Customers Evaluated", value=f"{len(df):,}")
    with col2:
        st.metric(label="High Risk Churners (≥70%)", value=f"{len(high_risk):,}")
    with col3:
        revenue_at_risk = whales_at_risk['MonthlyRevenue'].sum()
        st.metric(label="Revenue at Risk (The 'Whales')", value=f"${revenue_at_risk:,.2f}")
        
    st.markdown("---")
    
    # --- PRIORITY ACTION LIST ---
    st.markdown("### Priority Action List (The Whales)")
    st.markdown("These customers meet the intervention criteria. Dispatch retention offers immediately.")
    
    # Select the updated columns, including RoamingCalls and TFI
    display_cols = ['Churn_Probability', 'MonthlyRevenue', 'TFI', 'DroppedCalls', 'RoamingCalls', 'OverageMinutes']
    display_df = whales_at_risk[display_cols].copy()
    
    # Format the data for a clean, executive view
    display_df['Churn_Probability'] = (display_df['Churn_Probability'] * 100).round(1).astype(str) + "%"
    display_df['MonthlyRevenue'] = "$" + display_df['MonthlyRevenue'].round(2).astype(str)
    display_df['TFI'] = display_df['TFI'].round(2)
    
    # Sort worst offenders to the top (Highest Probability, then Highest Revenue)
    display_df = display_df.sort_values(by=['Churn_Probability', 'MonthlyRevenue'], ascending=[False, False])
    
    st.dataframe(display_df.head(100), use_container_width=True)
